### ISSUE TITLE
Displaying GIFs

### ISSUE THREAD

**Issue by izaharkin** [karolzak/ipyplot#18]
Hi there!

Thank you for the project, found it pretty helpful :)

Unfortunately, I didn't find any way to display a grid of GIFs (.gif files). Could you please help with setting the right arguments, or should It be [Feature Request] issue?

Thank you!

**Comment by karolzak** [comment]
Hi @izaharkin 
Thanks for stoping by and glad you like it!

As for using GIFs (as far as I know) there should be no issue using them the same way as .jpg or .png files.  
Did you try running IPyPlot with gifs and it failed for you somehow?

Here's an example that I just tested and it works correctly for me:
```python
img_paths = ['docs\\example1-tabs.gif', # gif file
  'docs\\example1-tabs.jpg',
  'docs\\example2-images.jpg',
  'docs\\example3-classes.jpg']

import ipyplot

ipyplot.plot_images(img_paths)
```

Just make sure that the image file URLs are relative paths and are either on the same level or below the level of where your jupyter server was started.
