### ISSUE TITLE
[Feature request] Allow hide urls from the plot

### ISSUE THREAD

**Issue by BrikerMan** [karolzak/ipyplot#19]
Thanks for the great framework, it helps a lot. But I need to hide the URLs from the plot so I can focus on the images. Cab we add that feature?

**Comment by karolzak** [comment]
Hi @BrikerMan 
It makes perfect sense to me. I'll put this in the backlog - thanks!

**Comment by Maarten-vr** [comment]
Hi @karolzak, is there any progress on this topic or is there a quick workaround?
It is a nice package for convenience, but the url are making the output quite messy in my case.

**Comment by karolzak** [comment]
Hey @Maarten-vr
Was busy with other stuff lately so this feature got buried and forgotten but since it's a minor enhancement I will try to add it before the winter holidays

**Comment by Maarten-vr** [comment]
I've dug into the code myself as well and made it work.
I've created a PR so you can use the code (either directly, or improve upon it)

**Comment by karolzak** [comment]
@Maarten-vr that's a rockstar move!
Thank you so much for this contribution! I will review it and merge ASAP!

![](https://i.pinimg.com/originals/dd/76/04/dd76044217f67ca536896b4939911a5b.gif)

**Comment by karolzak** [comment]
Thanks @BrikerMan for this suggestion and thank you @Maarten-vr for implementing it!
This feature is now available in version 1.1.1

**Comment by Alyetama** [comment]
> Thanks @BrikerMan for this suggestion and thank you @Maarten-vr for implementing it!
> This feature is now available in version 1.1.1

Just FYI, version 1.1.1 is not on PyPi yet.
