### ISSUE TITLE
img_width doesn't seem to work for urls?

### ISSUE THREAD

**Issue by littlehome-eugene** [karolzak/ipyplot#23]
<img width="721" alt="스크린샷 2020-11-22 오후 3 13 33" src="https://user-images.githubusercontent.com/24217396/99896613-840c8000-2cd5-11eb-9c54-3db6771e100d.png">

I'm trying to show multiple images in a row with `img_width` but it doesn't seem to work as expected.

**Comment by karolzak** [comment]
Hey @littlehome-eugene 
I don't think it's related to `img_width`. It looks like the CSS style was not injected properly or even removed from HTML.
What environment are you running it in? Is this a standard Jupyter Server or something like Google Colab?

**Comment by karolzak** [comment]
Closing due to no response
