### ISSUE TITLE
Warning about colab runtime could be a tad more helpful/precise (base_64)

### ISSUE THREAD

**Issue by davidefiocco** [karolzak/ipyplot#37]
Hi!

I think that in https://github.com/karolzak/ipyplot/blob/ff64f4a376e17bf86c6c6fb1d47ee99e50227708/ipyplot/__init__.py#L26 I the warning should refer to `force_b64` (not `base_64`) to fix problems that may occur in Google colab.

**Comment by karolzak** [comment]
Good catch @davidefiocco, thanks for fixing it!
