### ISSUE TITLE
[Docs] add back examples that can be copy/pasted in readme

### ISSUE THREAD

**Issue by rom1504** [karolzak/ipyplot#40]
screenshots are nice but not convenient

**Comment by karolzak** [comment]
Thanks for your feedback @rom1504 !
I showcased all the code examples in this [notebook](https://github.com/karolzak/ipyplot/blob/master/notebooks/gear-images-examples.ipynb) but I totally see how it would be useful to have at least some base examples directly in readme - I'll make sure to add it, thanks!
