### ISSUE TITLE
Sort images in plot_class_tabs

### ISSUE THREAD

**Issue by segalinc** [karolzak/ipyplot#47]
Hello there, thank you for your library !

Looking for a way to:
given a panda dataframe, where colums are [image_path, class, value] , display plot_class_tabs where labels is class column and images are visualized sorted based on value column

thank you

**Comment by karolzak** [comment]
Hey @segalinc ! Thanks for kind words!
Since this is closed now, I assume you found out how to do it already?

**Comment by segalinc** [comment]
Hi, yes
It might not be the best solution but I found a way,
Just had to build a new exploded dataframe where for every class I repeat
all the images but sorted so that the algo pickes up all the images sorted
already when filters by the class
If you had a better solution is also welcome!
