### ISSUE TITLE
Adding caption to each image

### ISSUE THREAD

**Issue by harsh-99** [karolzak/ipyplot#5]
Hi, 
Thanks for your contribution. Just wanted to know if there is any option to add caption to each figure?

**Comment by karolzak** [comment]
Hi @harsh-99 !
Could you give more details there? Do you mean a caption for each displayed image like below?
![image](https://user-images.githubusercontent.com/9843623/85938319-70b6dd80-b90c-11ea-9513-87496cceb559.png)

If yes then you just need to use the `labels` arg for `ipyplot.plot_images` function and provide a specific `string` for each image you want to display:
```python
import ipyplot
import numpy as np

imgs = np.random.randint(0, 255, (3,128,128,3), np.uint8)

ipyplot.plot_images(imgs, labels = ['caption a', 'caption b', 'other caption c'])
``` 

Or are you talking about different captions?

**Comment by harsh-99** [comment]
Hi,
Thanks a lot for the help. I missed out to check this option. 

Thanks once again.!
