### ISSUE TITLE
numpy 1.20+ does't have `np.float`

### ISSUE THREAD

**Issue by nesaboz** [karolzak/ipyplot#50]
When trying basic: `ipyplot.plot_images([np.array([1,2])])` I get:

`AttributeError: module 'numpy' has no attribute 'float'`

This is due to [this](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) depreciation.

**Comment by karolzak** [comment]
Thank you @nesaboz for bringing up this issue and @ricoms - thanks for the fix!

**Comment by karolzak** [comment]
This fix is now published to PyPI with release version 1.1.2.
Thanks again for your contributions!
