### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'.

### ISSUE THREAD

**Issue by hhh-0** [karolzak/ipyplot#59]
With numpy version 1.25.2 installed, ipyplot.plot_images() gives AttributeError: module 'numpy' has no attribute 'float'.

It looks like the fix (https://github.com/karolzak/ipyplot/pull/51 ) is merged but due to build fail, the latest version isn't available in PyPI.

**Comment by ami-navon** [comment]
+1

**Comment by oroelipas** [comment]
+1

**Comment by oroelipas** [comment]
Ok, I think I found the reason: 

#51 fixed the error in January 2023 but the last release available ([1.1.1](https://github.com/karolzak/ipyplot/releases/tag/1.1.1)) is from March 2022, so it is not included yet in the PyPi repositories.

You can install the latest version from the github source code with this pip command:

`pip install --upgrade --force-reinstall git+https://github.com/karolzak/ipyplot`

(Remember to restart the python environment and reload libraries again to have the new installed version)

This worked for me.

**Comment by recursix** [comment]
should someone upgrade the PyPi?

**Comment by karolzak** [comment]
Thanks everyone for raising this issue. I finally fixed the publish process and released the new package to PyPI with 1.1.2 version so there's no need for hacks and workarounds anymore :)
Thank you all for your patience!
