### ISSUE TITLE
Can't plot more than 30 images at once.

### ISSUE THREAD

**Issue by aseemarora1995** [karolzak/ipyplot#7]
I have a list which contains 120 images, but only the first 30 images get plotted.

**Comment by karolzak** [comment]
Hi @aseemarora1995 
Can you provide more details on your image list? Is it a list of numpy.array or list of URIs?
Which function are you using for plotting and what are the parameters you're using?
Each ipyplot function have an argument which is responsible for limiting down the number of plotted images to a certain number, maybe you need to change that value in your case.
